name: learn-github-actions
on: [ push ]

jobs:
  run-build:
    name: run build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Build DockerContainer
        shell: bash
        run: |
            docker build --build-arg NPM_TOKEN=${{ secrets.NPM_ARTIFACTORY_TOKEN }} -t my_test .
      - name: Run Unit Tests
        shell: bash
        run: |
            docker run my_test npm run test
